apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: wordpress
  namespace: vela-system
  annotations:
    definition.oam.dev/description: "Wordpress component"
spec:
  workload:
    definition:
      apiVersion: apps/v1
      kind: Deployment
  schematic:
    cue:
      template: |
        output: {
          apiVersion: "apps/v1"
          kind:       "Deployment"
          spec: {
            selector: matchLabels: {
              "app.oam.dev/component": context.name
              if parameter.addRevisionLabel {
                "app.oam.dev/appRevision": context.appRevision
              }
            }
            template: {
              metadata: labels: {
                "app.oam.dev/component": context.name
                if parameter.addRevisionLabel {
                  "app.oam.dev/appRevision": context.appRevision
                }
              }
              spec: {
                containers: [{
                  name: context.name
                  image: parameter.image

                  ports: [{
                    containerPort: parameter.port
                  }]

                  if parameter["env"] != _|_ {
                    env: parameter.env
                  }

                }]
              }
            }
          }
        }   
        parameter: {
          // +usage=Which image would you like to use for your service
          // +short=i
          image: *"bitnami/wordpress:5.8.1" | string

          // +usage=Which port do you want customer traffic sent to
          // +short=p
          port: *8080 | int

          // +usage=Define arguments by using environment variables
          env: *[{name:"ALLOW_EMPTY_PASSWORD", value:"yes"}, 
                 {name:"WORDPRESS_DATABASE_HOST", value:"mysql-db"},
                 {name:"MYSQL_CLIENT_DATABASE_HOST", value:"mysql-db"},
                 {name:"WORDPRESS_DATABASE_USER", value:"root"},
                 {name:"MYSQL_CLIENT_FLAVOR", value:"mysql"},
                 {name:"MYSQL_CLIENT_CREATE_DATABASE_NAME", value:"bitnami_wordpress"}] | [...{
            // +usage=Environment variable name
            name: string
            // +usage=The value of the environment variable
            value?: string
            // +usage=Specifies a source the value of this var should come from
            valueFrom?: {
              // +usage=Selects a key of a secret in the pod's namespace
              secretKeyRef: {
                // +usage=The name of the secret in the pod's namespace to select from
                name: string
                // +usage=The key of the secret to select from. Must be a valid secret key
                key: string
              }
            }
          }]          

          // If addRevisionLabel is true, the appRevision label will be added to the underlying pods 
          addRevisionLabel: *false | bool
        }