apiVersion: core.oam.dev/v1alpha2
kind: HealthScope
metadata:
  name: wp-health-check
  namespace: vela-system
spec:
  probe-interval: 60
  workloadRefs:
  - apiVersion: apps/v1
    kind: Deployment
    name: mysql-db
  - apiVersion: apps/v1
    kind: Deployment
    name: wordpress-site